# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Body(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, answer: str=None):  # noqa: E501
        """Body - a model defined in Swagger

        :param answer: The answer of this Body.  # noqa: E501
        :type answer: str
        """
        self.swagger_types = {
            'answer': str
        }

        self.attribute_map = {
            'answer': 'answer'
        }
        self._answer = answer

    @classmethod
    def from_dict(cls, dikt) -> 'Body':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body of this Body.  # noqa: E501
        :rtype: Body
        """
        return util.deserialize_model(dikt, cls)

    @property
    def answer(self) -> str:
        """Gets the answer of this Body.


        :return: The answer of this Body.
        :rtype: str
        """
        return self._answer

    @answer.setter
    def answer(self, answer: str):
        """Sets the answer of this Body.


        :param answer: The answer of this Body.
        :type answer: str
        """

        self._answer = answer
