# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, participated: bool=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param participated: The participated of this InlineResponse200.  # noqa: E501
        :type participated: bool
        """
        self.swagger_types = {
            'participated': bool
        }

        self.attribute_map = {
            'participated': 'participated'
        }
        self._participated = participated

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def participated(self) -> bool:
        """Gets the participated of this InlineResponse200.


        :return: The participated of this InlineResponse200.
        :rtype: bool
        """
        return self._participated

    @participated.setter
    def participated(self, participated: bool):
        """Sets the participated of this InlineResponse200.


        :param participated: The participated of this InlineResponse200.
        :type participated: bool
        """

        self._participated = participated
